export interface Product {
  slug: string;
  title: string;
  priceStr: string;
  priceNum: number;
  category: string;
  categorySlug: string;
  image: string;
  keywords?: string;
  format?: string;
  description?: string;
}

export const CATEGORIES = [
  { slug: "all", label: "Alle" },
  { slug: "vibration-codes", label: "Soundhealing" },
  { slug: "gefuehrte-meditation", label: "Geführte Meditation" },
  { slug: "soundtrack", label: "Soundtrack" },
  { slug: "hildegard-original", label: "Hildegard Original" },
  { slug: "hildegard-modern", label: "Hildegard Modern" },
];

export const PRODUCTS: Product[] = [
  {
    slug: "tanz-des-fauns",
    title: "Tanz des Fauns",
    priceStr: "18,99€",
    priceNum: 18.99,
    category: "Vibration Codes – Soundhealing",
    categorySlug: "vibration-codes",
    image: "/images/shop/tanz-des-fauns.jpg",
    keywords: "Leichtigkeit · Erdverbundenheit · Lebensfreude",
    format: "Digitaler Download | WAV-Audio File | 16:00 min",
    description: "Erlebe in diesem Musikstück die harmonische Verbindung von Erdverbundenheit und wohliger Leichtigkeit. Die sanfte Melodie der Doppelflöte lädt dich ein, den Stress des Alltags hinter dir zu lassen und in eine entspannende Klanglandschaft einzutauchen. In der Mythologie ist der Faun Hüter des Waldes und Beschützer der Tiere. Er ist ein fröhliches, friedvolles Wesen, das mit seiner Sanftmut und Weisheit die Balance in der Welt fördert. Tanze mit dem Faun durch unberührte Natur und genieße die Lebensfreude und Leichtigkeit des Seins.",
  },
  {
    slug: "raum-der-kristalle",
    title: "Raum der Kristalle",
    priceStr: "18,99€",
    priceNum: 18.99,
    category: "Vibration Codes – Soundhealing",
    categorySlug: "vibration-codes",
    image: "/images/shop/raum-der-kristalle.jpg",
    keywords: "Reinigung · Klarheit · Erneuerung",
    format: "Digitaler Download | WAV-Audio File | 22:03 min",
    description: "Diese Klänge von Kristallschalen und Kristallpyramide nehmen dich mit auf eine transformative Reise der Reinigung. Ihre binauralen Klänge helfen, Spannungen zu lösen und dich durchlässig zu machen für neue Energien. Die sanft umhüllenden und klaren Schwingungen der Kristallinstrumente laden dich in einen Raum ein, der von einer erfrischenden Brise durchzogen ist.",
  },
  {
    slug: "morgen",
    title: "Morgen!",
    priceStr: "18,99€",
    priceNum: 18.99,
    category: "Vibration Codes – Soundhealing",
    categorySlug: "vibration-codes",
    image: "/images/shop/morgen.jpg",
    keywords: "Neubeginn · Energie · Ausrichtung",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Eine kraftvolle Klangmeditation für den Morgen – starte bewusst und energiegeladen in deinen Tag.",
  },
  {
    slug: "moegen-alle-wesen-gluecklich-sein",
    title: "Mögen alle Wesen glücklich sein",
    priceStr: "18,99€",
    priceNum: 18.99,
    category: "Vibration Codes – Soundhealing",
    categorySlug: "vibration-codes",
    image: "/images/shop/moegen-alle-wesen.jpg",
    keywords: "Mitgefühl · Liebe · Verbundenheit",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Liebevolle Klänge, inspiriert vom Metta-Gedanken. Diese Meditation öffnet das Herz und stärkt Mitgefühl – für dich selbst und alle Wesen.",
  },
  {
    slug: "geschenk-der-inspiration",
    title: "Geschenk der Inspiration",
    priceStr: "18,99€",
    priceNum: 18.99,
    category: "Vibration Codes – Soundhealing",
    categorySlug: "vibration-codes",
    image: "/images/shop/geschenk-der-inspiration.jpg",
    keywords: "Kreativität · Intuition · Öffnung",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Öffne dich für neue Impulse und kreative Energie. Diese Klangmeditation aktiviert deine Intuition und deinen schöpferischen Geist.",
  },
  {
    slug: "die-himmel-erzaehlen",
    title: "Die Himmel erzählen",
    priceStr: "18,99€",
    priceNum: 18.99,
    category: "Vibration Codes – Soundhealing",
    categorySlug: "vibration-codes",
    image: "/images/shop/die-himmel-erzaehlen.jpg",
    keywords: "Weite · Stille · Verbundenheit",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Eine erhabene Klangmeditation, die dich mit der Weite des Universums verbindet.",
  },
  {
    slug: "lotosblume",
    title: "Lotosblume",
    priceStr: "18,99€",
    priceNum: 18.99,
    category: "Vibration Codes – Soundhealing",
    categorySlug: "vibration-codes",
    image: "/images/shop/lotosblume.jpg",
    keywords: "Reinheit · Erwachen · Entfaltung",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Symbol der Reinheit und des Erwachens – so wie die Lotosblume aus dem Schlamm ins Licht wächst.",
  },
  {
    slug: "lias-song",
    title: "Lias Song",
    priceStr: "18,99€",
    priceNum: 18.99,
    category: "Vibration Codes – Soundhealing",
    categorySlug: "vibration-codes",
    image: "/images/shop/lias-song.jpg",
    keywords: "Wärme · Liebe · Geborgenheit",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Ein berührendes Klangstück voller Wärme und Liebe.",
  },
  {
    slug: "flug-des-phoenix",
    title: "Flug des Phönix",
    priceStr: "18,99€",
    priceNum: 18.99,
    category: "Vibration Codes – Soundhealing",
    categorySlug: "vibration-codes",
    image: "/images/shop/flug-des-phoenix.jpg",
    keywords: "Transformation · Wandel · Erneuerung",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Transformation und Wiedergeburt – diese kraftvolle Klangmeditation unterstützt dich in Zeiten des Wandels.",
  },
  {
    slug: "fuenf-lichter-mantra",
    title: "Fünf Lichter Mantra",
    priceStr: "19,98€",
    priceNum: 19.98,
    category: "Geführte Meditation",
    categorySlug: "gefuehrte-meditation",
    image: "/images/shop/fuenf-lichter-mantra.jpg",
    keywords: "Stille · Führung · Bewusstsein",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Eine tiefe geführte Meditation mit dem Fünf-Lichter-Mantra. Antonia begleitet dich mit ihrer Stimme in einen Zustand tiefer innerer Stille.",
  },
  {
    slug: "zeit-zum-neubeginn-meditation",
    title: "Zeit zum Neubeginn – Geführte Meditation",
    priceStr: "19,98€",
    priceNum: 19.98,
    category: "Geführte Meditation",
    categorySlug: "gefuehrte-meditation",
    image: "/images/shop/zeit-zum-neubeginn.jpg",
    keywords: "Loslassen · Neubeginn · Transformation",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Eine geführte Reise zu deinem inneren Neuanfang. Diese Meditation hilft dir, Altes loszulassen und mit Leichtigkeit in neue Lebensabschnitte einzutreten.",
  },
  {
    slug: "zeit-zum-neubeginn",
    title: "Zeit zum Neubeginn",
    priceStr: "15,39€",
    priceNum: 15.39,
    category: "Soundtrack",
    categorySlug: "soundtrack",
    image: "/images/shop/zeit-zum-neubeginn.jpg",
    keywords: "Instrumentalmusik · Entspannung · Hintergrundmusik",
    format: "Digitaler Download | WAV-Audio File",
    description: "/* Beschreibung ergänzen */ Der instrumentale Soundtrack – reine Klanglandschaften ohne gesprochene Führung, ideal als Hintergrundmusik für Meditation und Entspannung.",
  },
  {
    slug: "o-viridissima-virga-original",
    title: "O viridissima virga",
    priceStr: "3,99€",
    priceNum: 3.99,
    category: "Hildegard von Bingen – Originalgesang",
    categorySlug: "hildegard-original",
    image: "/images/shop/o-viridissima-virga-original.jpg",
    keywords: "Hildegard · Originalgesang · Mittelalter",
    format: "Digitaler Download | WAV-Audio File",
    description: "Hildegards Hymne an die grünende Kraft – authentisch und unverfälscht aufgenommen von Antonia Braditsch. Ein meditativer Gesang, der die Seele berührt.",
  },
  {
    slug: "o-quam-mirabilis-original",
    title: "O quam mirabilis",
    priceStr: "3,99€",
    priceNum: 3.99,
    category: "Hildegard von Bingen – Originalgesang",
    categorySlug: "hildegard-original",
    image: "/images/shop/o-quam-mirabilis-original.jpg",
    keywords: "Hildegard · Originalgesang · Weisheit",
    format: "Digitaler Download | WAV-Audio File",
    description: "O wie wunderbar – Hildegards Lied über die Weisheit Gottes. Original aufgenommen von Antonia Braditsch in mittelalterlicher Tradition.",
  },
  {
    slug: "o-ignis-spiritus-original",
    title: "O ignis spiritus",
    priceStr: "3,99€",
    priceNum: 3.99,
    category: "Hildegard von Bingen – Originalgesang",
    categorySlug: "hildegard-original",
    image: "/images/shop/o-ignis-spiritus-original.jpg",
    keywords: "Hildegard · Originalgesang · Heiliger Geist",
    format: "Digitaler Download | WAV-Audio File",
    description: "O Feuer des Geistes – eine kraftvolle Sequenz Hildegards an den Heiligen Geist. Authentisch gesungen von Antonia Braditsch.",
  },
  {
    slug: "ave-maria-original",
    title: "Ave, Maria, o auctrix vitae",
    priceStr: "3,99€",
    priceNum: 3.99,
    category: "Hildegard von Bingen – Originalgesang",
    categorySlug: "hildegard-original",
    image: "/images/shop/ave-maria-original.jpg",
    keywords: "Hildegard · Maria · Originalgesang",
    format: "Digitaler Download | WAV-Audio File",
    description: "Hildegards Ave Maria – eine bewegende Antiphon, die Maria als Urheberin des Lebens feiert. Original aufgenommen von Antonia Braditsch.",
  },
  {
    slug: "o-viridissima-virga-modern",
    title: "O viridissima virga",
    priceStr: "9,99€",
    priceNum: 9.99,
    category: "Hildegard von Bingen – Modern Mystic Music",
    categorySlug: "hildegard-modern",
    image: "/images/shop/o-viridissima-virga-modern.jpg",
    keywords: "Hildegard · Modern · Mystik",
    format: "Digitaler Download | WAV-Audio File",
    description: "Hildegards 'O viridissima virga' in modernem Gewand – eine Brücke zwischen mittelalterlicher Mystik und zeitgenössischer Klangwelt.",
  },
  {
    slug: "o-quam-mirabilis-modern",
    title: "O quam mirabilis",
    priceStr: "9,99€",
    priceNum: 9.99,
    category: "Hildegard von Bingen – Modern Mystic Music",
    categorySlug: "hildegard-modern",
    image: "/images/shop/o-quam-mirabilis-modern.jpg",
    keywords: "Hildegard · Modern · Weisheit",
    format: "Digitaler Download | WAV-Audio File",
    description: "Modern arrangiert und neu interpretiert – Hildegards Weisheitshymne in einer zeitlosen Fassung für die heutige Zeit.",
  },
  {
    slug: "o-ignis-spiritus-modern",
    title: "O ignis spiritus",
    priceStr: "9,99€",
    priceNum: 9.99,
    category: "Hildegard von Bingen – Modern Mystic Music",
    categorySlug: "hildegard-modern",
    image: "/images/shop/o-ignis-spiritus-modern.jpg",
    keywords: "Hildegard · Modern · Feuer",
    format: "Digitaler Download | WAV-Audio File",
    description: "Das Feuer des Geistes, neu entfacht – Hildegards kraftvolle Sequenz in moderner Klangsprache arrangiert.",
  },
  {
    slug: "ave-maria-modern",
    title: "Ave, Maria, o auctrix vitae",
    priceStr: "9,99€",
    priceNum: 9.99,
    category: "Hildegard von Bingen – Modern Mystic Music",
    categorySlug: "hildegard-modern",
    image: "/images/shop/ave-maria-modern.jpg",
    keywords: "Hildegard · Modern · Maria",
    format: "Digitaler Download | WAV-Audio File",
    description: "Hildegards Ave Maria neu gedacht – eine zeitgenössische Interpretation des mittelalterlichen Originals.",
  },
];

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string) {
  if (categorySlug === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.categorySlug === categorySlug);
}
